-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Startti CASCADE;
DROP TABLE IF EXISTS Lenkki CASCADE;
DROP TABLE IF EXISTS Tapahtuma CASCADE;
DROP TABLE IF EXISTS Osallistuja CASCADE;
DROP TABLE IF EXISTS Juoksija CASCADE;
